config/routes.rb
Rails.application.routes.draw do
  resources :vehicules
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicule.rb
class Vehicule < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/vehicules_controller.rb
class VehiculesController < InheritedResources::Base
  def index
    @vehicules = Vehicule.where(["owner_name LIKE ?", "%#{params[:search]}%"])
  end
  private

    def vehicule_params
      params.require(:vehicule).permit(:date, :owner_name, :N°cin, :vehicules_type, :mark, :color, :N°engine)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vehicules_helper.rb
module VehiculesHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Drimo</title>
    <!--    favicon-->
    <link rel="shortcut icon" href="image/fav-icon.png" type="image/x-icon">
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/themify-icons.css">
    <link rel="stylesheet" href="css/animate.css">
    <!--css-->
    <link rel="stylesheet" href="css/style.css">
    <!-- HTmL5 shim and Respond.js for IE8 support of HTmL5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
</head>

<body>
    <section class="hero-area-fix">
        <div class="hero-area" id="water">
            <div class="container">
                <div class="row">
                    <div class="hero-text">
                        <h1>Drimo</h1>
                        <div id="typed-strings">
                            <h3>Drimo App Landing Page Template</h3>
                            <h3>Drimo Android Template</h3>
                            <h3>Drimo Apple iso</h3>
                        </div>
                        <h3><span id="typed"></span></h3>
                        <h4>A Complete Landing Page and Multipurpose Package</h4>
                        <a href="#" class="btn view-demo" data-scroll-nav="1">View Demos</a>
                        <a href="#" class="btn buy-now">Buy Drimo</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="product-landing pro_d" data-scroll-index="1">
        <div class="container">
            <div class="row">
                <h2 class="title">Home onepage Demos</h2>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-1.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 01</p>
                        </div>
                    </a>
                </div>
                <div class="container">
                <%= form_tag vehicules_path, :method => 'get' do %>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Search" %>
                <% end %>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-2.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-2.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 02</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-3.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-3.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 03</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-4.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-4.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 04</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-5.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-5.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 05</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-6.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-6.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 06</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-7.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-7.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 07</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-8.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-8.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 08</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-9.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-9.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 09</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-10.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-10.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 10</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <a href="drimo/index-11.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/index-11.png" class="img-responsive radius" alt="">
                            <p class="product-title">OnePage - 11</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <section class="saas-landing">
        <div class="container">
            <div class="row">
                <h2 class="title">Drimo Blog Page Demos</h2>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a href="drimo/blog.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/blog-1.png" class="img-responsive radius" alt="">
                            <p class="product-title">Blog List - 01</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a href="drimo/blog-right-sidebar.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/blog-2.png" class="img-responsive radius" alt="">
                            <p class="product-title">Blog List - 02</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a href="drimo/single-blog.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/blog-3.png" class="img-responsive radius" alt="">
                            <p class="product-title">Blog Details</p>
                        </div>
                    </a>
                </div>
                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a href="drimo/404.html" target="_blank">
                        <div class="item-imag">
                            <img src="image/product/error_page.png" class="img-responsive radius" alt="">
                            <p class="product-title">Error</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <footer class="footer-area">
        <div class="container">
            <div class="row text-center">
                <p class="copyright">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
            </div>
        </div>
    </footer>
    <!--End Footer area-->
    <script src="js/jquery-2.2.4.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/nav.js"></script>
    <!--waypoint js-->
    <script src="vendor/waypoint/waypoints.min.js"></script>
    <!--counter js-->
    <script src="vendor/couterup/jquery.counterup.min.js"></script>
    <script src="vendor/typedjs/typed.min.js"></script>
    <script src="vendor/ripples/jquery.ripples-min.js"></script>
    <script type="text/javascript" src="js/scrollIt.min.js"></script>
    <script type="text/javascript" src="js/wow.js"></script>
    <script src="js/custom.js"></script>
    <script>
    $(function() {
        $.scrollIt();
    });
    </script>
    <script>
    new WOW().init();
    </script>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicules/_form.html.erb
<%= form_with(model: vehicule, local: true) do |form| %>
  <% if vehicule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicule.errors.count, "error") %> prohibited this vehicule from being saved:</h2>

      <ul>
      <% vehicule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date %>
  </div>

  <div class="field">
    <%= form.label :owne_name %>
    <%= form.text_field :owne_name %>
  </div>

  <div class="field">
    <%= form.label :N°cin %>
    <%= form.number_field :N°cin %>
  </div>

  <div class="field">
    <%= form.label :vehicules_type %>
    <%= form.text_field :vehicules_type %>
  </div>

  <div class="field">
    <%= form.label :mark %>
    <%= form.text_field :mark %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :N°engine %>
    <%= form.text_field :N°engine %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicules/edit.html.erb
<h1>Editing Vehicule</h1>

<%= render 'form', vehicule: @vehicule %>

<%= link_to 'Show', @vehicule %> |
<%= link_to 'Back', vehicules_path %>

app/views/vehicules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicules</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Owne name</th>
      <th>N°cin</th>
      <th>Vehicules type</th>
      <th>Mark</th>
      <th>Color</th>
      <th>N°engine</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicules.each do |vehicule| %>
      <tr>
        <td><%= vehicule.date %></td>
        <td><%= vehicule.owner_name %></td>
        <td><%= vehicule.N°cin %></td>
        <td><%= vehicule.vehicules_type %></td>
        <td><%= vehicule.mark %></td>
        <td><%= vehicule.color %></td>
        <td><%= vehicule.N°engine %></td>
        <td><%= link_to 'Show', vehicule %></td>
        <td><%= link_to 'Edit', edit_vehicule_path(vehicule) %></td>
        <td><%= link_to 'Destroy', vehicule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  
  </tbody>
</table>

<br>

<%= link_to 'New Vehicule', new_vehicule_path %>

app/views/vehicules/new.html.erb
<h1>New Vehicule</h1>

<%= render 'form', vehicule: @vehicule %>

<%= link_to 'Back', vehicules_path %>

app/views/vehicules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @vehicule.date %>
</p>

<p>
  <strong>Owne name:</strong>
  <%= @vehicule.owne_name %>
</p>

<p>
  <strong>N°cin:</strong>
  <%= @vehicule.N°cin %>
</p>

<p>
  <strong>Vehicules type:</strong>
  <%= @vehicule.vehicules_type %>
</p>

<p>
  <strong>Mark:</strong>
  <%= @vehicule.mark %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicule.color %>
</p>

<p>
  <strong>N°engine:</strong>
  <%= @vehicule.N°engine %>
</p>

<%= link_to 'Edit', edit_vehicule_path(@vehicule) %> |
<%= link_to 'Back', vehicules_path %>